# Generated by Django 3.2.8 on 2021-12-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdCredential',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('credentialcode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'pd_credential',
            },
        ),
        migrations.CreateModel(
            name='PdDrugs',
            fields=[
                ('drugid', models.IntegerField(primary_key=True, serialize=False)),
                ('drugname', models.CharField(max_length=30, unique=True)),
                ('isopioid', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='PdPrescriber',
            fields=[
                ('npi', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=5)),
                ('totalprescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='PdStatedata',
            fields=[
                ('state', models.CharField(max_length=14)),
                ('stateabbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='PdTriple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('drugname', models.ForeignKey(db_column='drugname', on_delete=django.db.models.deletion.CASCADE, to='DrugApp.pddrugs', to_field='drugname')),
                ('prescriberid', models.ForeignKey(db_column='prescriberid', on_delete=django.db.models.deletion.CASCADE, to='DrugApp.pdprescriber')),
            ],
            options={
                'db_table': 'pd_triple',
            },
        ),
        migrations.CreateModel(
            name='PdPrescriberCredential',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('credential', models.ForeignKey(db_column='credentialcode', on_delete=django.db.models.deletion.CASCADE, to='DrugApp.pdcredential', to_field='credentialcode')),
                ('prescriberid', models.ForeignKey(db_column='prescriberid', on_delete=django.db.models.deletion.CASCADE, to='DrugApp.pdprescriber')),
            ],
            options={
                'db_table': 'pd_prescriber_credential',
            },
        ),
        migrations.AddField(
            model_name='pdprescriber',
            name='credentials',
            field=models.ManyToManyField(through='DrugApp.PdPrescriberCredential', to='DrugApp.PdCredential'),
        ),
        migrations.AddField(
            model_name='pdprescriber',
            name='drugs',
            field=models.ManyToManyField(through='DrugApp.PdTriple', to='DrugApp.PdDrugs'),
        ),
        migrations.AddField(
            model_name='pdprescriber',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='DrugApp.pdstatedata'),
        ),
    ]
