# Generated by Django 3.2.8 on 2021-12-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrugApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdprescribercredential',
            name='credential',
            field=models.ForeignKey(db_column='credential', on_delete=django.db.models.deletion.CASCADE, to='DrugApp.pdcredential', to_field='credentialcode'),
        ),
    ]
